import { TireItem } from './types';

export const INITIAL_TIRES: Omit<TireItem, 'id'>[] = [
  // Camal (15 items)
  {
    brand: 'Camal',
    size: '130/70-12',
    rim: '12',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-01',
    zone: 'ห้องยางชั้น 2',
    description: 'ยางสปอร์ต สกู๊ตเตอร์',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '110/70-13',
    rim: '13',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-02',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อหน้า NMAX / Aerox',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '130/70-13',
    rim: '13',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-03',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อหลัง NMAX',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '80/90-14',
    rim: '14',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-04',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อหน้า Click / Scoopy / Fino',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '90/90-14',
    rim: '14',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-05',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อหลัง Click / Scoopy',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '100/80-14',
    rim: '14',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-06',
    zone: 'ห้องยางชั้น 2',
    description: 'PCX 150 ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '110/70-14',
    rim: '14',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-07',
    zone: 'ห้องยางชั้น 2',
    description: 'PCX 160 / Aerox ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '110/80-14',
    rim: '14',
    systemQty: 3,
    actualQty: 3,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-08',
    zone: 'ห้องยางชั้น 2',
    description: 'ADV 150/160 ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '120/70-14',
    rim: '14',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-09',
    zone: 'ห้องยางชั้น 2',
    description: 'PCX 150/160 ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '140/70-14',
    rim: '14',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-10',
    zone: 'ห้องยางชั้น 2',
    description: 'Aerox / Forza ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '120/70-15',
    rim: '15',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-11',
    zone: 'ห้องยางชั้น 2',
    description: 'XMAX / Forza ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '100/80-17',
    rim: '17',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-12',
    zone: 'ห้องยางชั้น 2',
    description: 'ยางรถสปอร์ต 150cc ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '110/70-17',
    rim: '17',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-13',
    zone: 'ห้องยางชั้น 2',
    description: 'R15 / CBR150 ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '120/70-17',
    rim: '17',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-14',
    zone: 'ห้องยางชั้น 2',
    description: 'ยางบิ๊กไบค์ ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Camal',
    size: '130/70-17',
    rim: '17',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK A-15',
    zone: 'ห้องยางชั้น 2',
    description: 'CBR150 / R15 ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },

  // Fujiyama (8 items)
  {
    brand: 'Fujiyama',
    size: '100/90-10',
    rim: '10',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK B-01',
    zone: 'ห้องยางชั้น 2',
    description: 'สกู๊ตเตอร์ล้อ 10 นิ้ว',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Fujiyama',
    size: '120/70-12',
    rim: '12',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK B-02',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อหน้า MSX / Grand Filano',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Fujiyama',
    size: '110/70-13',
    rim: '13',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK B-03',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อหน้า NMAX',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Fujiyama',
    size: '110/70-14',
    rim: '14',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK B-04',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อหน้า Aerox',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Fujiyama',
    size: '110/70-17',
    rim: '17',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK B-05',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อหน้า สปอร์ต 150-300cc',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Fujiyama',
    size: '120/70-17',
    rim: '17',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK B-06',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อหน้า บิ๊กไบค์ Big Bike',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Fujiyama',
    size: '140/70-17',
    rim: '17',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK B-07',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อหลัง Ninja / CBR',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Fujiyama',
    size: '150/60-17',
    rim: '17',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK B-08',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อหลัง สปอร์ตบิ๊กไบค์ 300cc+',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },

  // Deestone (6 items)
  {
    brand: 'Deestone',
    size: '100/90-12',
    rim: '12',
    systemQty: 5,
    actualQty: 5,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK C-01',
    zone: 'ห้องยางชั้น 2',
    description: 'Scoopy-i ล้อ 12 นิ้ว หน้า',
    minStock: 3,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Deestone',
    size: '110/70-12',
    rim: '12',
    systemQty: 7,
    actualQty: 7,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK C-02',
    zone: 'ห้องยางชั้น 2',
    description: 'Grand Filano / Scoopy-i หลัง',
    minStock: 3,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Deestone',
    size: '110/90-12',
    rim: '12',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK C-03',
    zone: 'ห้องยางชั้น 2',
    description: 'Scoopy-i ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Deestone',
    size: '120/70-12',
    rim: '12',
    systemQty: 5,
    actualQty: 5,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK C-04',
    zone: 'ห้องยางชั้น 2',
    description: 'MSX 125 ล้อหน้า / Vespa',
    minStock: 3,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Deestone',
    size: '130/70-12',
    rim: '12',
    systemQty: 6,
    actualQty: 6,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK C-05',
    zone: 'ห้องยางชั้น 2',
    description: 'MSX 125 ล้อหลัง',
    minStock: 3,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Deestone',
    size: '110/90-16',
    rim: '16',
    systemQty: 3,
    actualQty: 3,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK C-06',
    zone: 'ห้องยางชั้น 2',
    description: 'ล้อ 16 นิ้ว สกู๊ตเตอร์คลาสสิก',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },

  // Exella (17 items)
  {
    brand: 'Exella',
    size: '110/90-10',
    rim: '10',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-01',
    zone: 'ห้องยางชั้น 2',
    description: 'สกู๊ตเตอร์เรโทร 10 นิ้ว',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '120/70-10',
    rim: '10',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-02',
    zone: 'ห้องยางชั้น 2',
    description: 'Vespa ล้อหน้า 10 นิ้ว',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '110/70-11',
    rim: '11',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-03',
    zone: 'ห้องยางชั้น 2',
    description: 'Vespa LX / Primavera ล้อ 11',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '90/90-12',
    rim: '12',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-04',
    zone: 'ห้องยางชั้น 2',
    description: 'ยางหน้า 12 นิ้ว แคบ',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '120/70-12',
    rim: '12',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-05',
    zone: 'ห้องยางชั้น 2',
    description: 'MSX / Grand Filano',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '140/70-12',
    rim: '12',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-06',
    zone: 'ห้องยางชั้น 2',
    description: 'MSX ขยายไซส์หลัง / Vespa GTS',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '110/70-13',
    rim: '13',
    systemQty: 3,
    actualQty: 3,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-07',
    zone: 'ห้องยางชั้น 2',
    description: 'NMAX ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '130/70-13',
    rim: '13',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-08',
    zone: 'ห้องยางชั้น 2',
    description: 'NMAX ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '90/80-14',
    rim: '14',
    systemQty: 3,
    actualQty: 3,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-09',
    zone: 'ห้องยางชั้น 2',
    description: 'Click / Scoopy ล้อหน้าทรงสปอร์ต',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '100/90-14',
    rim: '14',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-10',
    zone: 'ห้องยางชั้น 2',
    description: 'PCX 150 ล้อหลัง / Click 160 หน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '110/70-14',
    rim: '14',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-11',
    zone: 'ห้องยางชั้น 2',
    description: 'PCX 160 / Aerox ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '120/70-14',
    rim: '14',
    systemQty: 3,
    actualQty: 3,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-12',
    zone: 'ห้องยางชั้น 2',
    description: 'PCX 160 ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '110/90-14',
    rim: '14',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-13',
    zone: 'ห้องยางชั้น 2',
    description: 'PCX / ADV สเปกสูง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '90/90-17',
    rim: '17',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-14',
    zone: 'ห้องยางชั้น 2',
    description: 'ยาง 17 นิ้ว หน้าสปอร์ต',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '110/70-17',
    rim: '17',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-15',
    zone: 'ห้องยางชั้น 2',
    description: 'CBR150 / R15 ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '130/70-17',
    rim: '17',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-16',
    zone: 'ห้องยางชั้น 2',
    description: 'CBR150 / R15 ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Exella',
    size: '140/70-17',
    rim: '17',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK D-17',
    zone: 'ห้องยางชั้น 2',
    description: 'R3 / Ninja 300 / CBR300 ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },

  // Veerubber (1 item)
  {
    brand: 'Veerubber',
    size: '100/90-14',
    rim: '14',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK E-01',
    zone: 'ห้องยางชั้น 2',
    description: 'ยาง Tubeless ทนทานสูง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },

  // Quick (3 items)
  {
    brand: 'Quick',
    size: '90/90-14',
    rim: '14',
    systemQty: 6,
    actualQty: 6,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK E-02',
    zone: 'ห้องยางชั้น 2',
    description: 'Click / Scoopy ล้อหลัง',
    minStock: 3,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Quick',
    size: '80/90-14',
    rim: '14',
    systemQty: 8,
    actualQty: 8,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK E-03',
    zone: 'ห้องยางชั้น 2',
    description: 'Click / Scoopy ล้อหน้า',
    minStock: 3,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Quick',
    size: '140/70-14',
    rim: '14',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK E-04',
    zone: 'ห้องยางชั้น 2',
    description: 'Aerox / Forza ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },

  // IRC (27 items)
  {
    brand: 'IRC',
    size: '90/90-12',
    rim: '12',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-01',
    zone: 'ห้องยางชั้น 2',
    description: 'Scoopy-i ล้อ 12 หน้า สเปกมาตรฐาน',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '100/90-12',
    rim: '12',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-02',
    zone: 'ห้องยางชั้น 2',
    description: 'Scoopy-i ล้อ 12 หน้ายอดนิยม',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '110/70-12',
    rim: '12',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-03',
    zone: 'ห้องยางชั้น 2',
    description: 'Grand Filano ล้อหน้า-หลัง (รุ่น A)',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '110/90-12',
    rim: '12',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-04',
    zone: 'ห้องยางชั้น 2',
    description: 'Scoopy-i ล้อ 12 หลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '110/70-12 (สปอร์ต)',
    rim: '12',
    systemQty: 3,
    actualQty: 3,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-05',
    zone: 'ห้องยางชั้น 2',
    description: 'Grand Filano / MSX สปอร์ตทัวริ่ง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '120/70-12',
    rim: '12',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-06',
    zone: 'ห้องยางชั้น 2',
    description: 'MSX 125 ล้อหน้า / Vespa',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '130/70-12',
    rim: '12',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-07',
    zone: 'ห้องยางชั้น 2',
    description: 'MSX 125 ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '140/70-12',
    rim: '12',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-08',
    zone: 'ห้องยางชั้น 2',
    description: 'MSX ล้อหลังไซส์ใหญ่ / Vespa GTS',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '110/70-13',
    rim: '13',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-09',
    zone: 'ห้องยางชั้น 2',
    description: 'NMAX ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '130/70-13',
    rim: '13',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-10',
    zone: 'ห้องยางชั้น 2',
    description: 'NMAX ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '80/90-14',
    rim: '14',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-11',
    zone: 'ห้องยางชั้น 2',
    description: 'Click / Scoopy ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '90/80-14',
    rim: '14',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-12',
    zone: 'ห้องยางชั้น 2',
    description: 'ยางสปอร์ต 14 นิ้ว หน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '90/90-14',
    rim: '14',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-13',
    zone: 'ห้องยางชั้น 2',
    description: 'Click / Scoopy ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '100/80-14',
    rim: '14',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-14',
    zone: 'ห้องยางชั้น 2',
    description: 'PCX 150 ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '100/90-14',
    rim: '14',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-15',
    zone: 'ห้องยางชั้น 2',
    description: 'Click 160 หน้า / PCX หลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '110/70-14',
    rim: '14',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-16',
    zone: 'ห้องยางชั้น 2',
    description: 'PCX 160 / Aerox ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '110/80-14',
    rim: '14',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-17',
    zone: 'ห้องยางชั้น 2',
    description: 'ADV 150/160 ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '110/90-14',
    rim: '14',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-18',
    zone: 'ห้องยางชั้น 2',
    description: 'PCX / ADV สเปกสูง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '120/70-14',
    rim: '14',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-19',
    zone: 'ห้องยางชั้น 2',
    description: 'PCX 160 ล้อหลัง • SCT-001 Mobicity',
    price: 1440,
    barcode: '8858722105389',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '140/70-14',
    rim: '14',
    systemQty: 2,
    actualQty: 2,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-20',
    zone: 'ห้องยางชั้น 2',
    description: 'Aerox / Forza ล้อหลัง สแตนดาร์ด',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '140/70-14 (Honda Forza)',
    rim: '14',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-21',
    zone: 'ห้องยางชั้น 2',
    description: 'IRC แท้ศูนย์ Honda Forza ล้อหลัง',
    minStock: 2,
    isOem: true,
    oemLabel: 'Honda Forza แท้ศูนย์',
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '120/70-15',
    rim: '15',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-22',
    zone: 'ห้องยางชั้น 2',
    description: 'Forza 300/350, XMAX ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '120/70-15 (Honda Forza)',
    rim: '15',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-23',
    zone: 'ห้องยางชั้น 2',
    description: 'IRC แท้ศูนย์ Honda Forza ล้อหน้า',
    minStock: 2,
    isOem: true,
    oemLabel: 'Honda Forza แท้ศูนย์',
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '70/90-17',
    rim: '17',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-24',
    zone: 'ห้องยางชั้น 2',
    description: 'Wave / Exciter ล้อหน้า',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '80/90-17',
    rim: '17',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-25',
    zone: 'ห้องยางชั้น 2',
    description: 'Wave / Exciter ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '120/70-17',
    rim: '17',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-26',
    zone: 'ห้องยางชั้น 2',
    description: 'ยางบิ๊กไบค์ ล้อหน้า 17',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'IRC',
    size: '130/70-17',
    rim: '17',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK F-27',
    zone: 'ห้องยางชั้น 2',
    description: 'CBR150 / R15 ล้อหลัง',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },

  // Other premium brands (Michelin, Pirelli, Maxxis - 3 items)
  {
    brand: 'Michelin',
    size: '110/70-14',
    rim: '14',
    systemQty: 0,
    actualQty: 0,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK G-01',
    zone: 'ห้องยางชั้น 2',
    description: 'Michelin City Grip 2 ล้อหน้า PCX 160 / Aerox',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Pirelli',
    size: '150/70-14',
    rim: '14',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK G-02',
    zone: 'ห้องยางชั้น 2',
    description: 'Pirelli Angel Scooter ล้อหลัง Forza / XMAX ไซส์ใหญ่',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    brand: 'Maxxis',
    size: '90/90-12',
    rim: '12',
    systemQty: 1,
    actualQty: 1,
    status: 'checked',
    category: 'Tubeless',
    location: 'RACK G-03',
    zone: 'ห้องยางชั้น 2',
    description: 'Maxxis Diamond ล้อ 12 หน้า Scoopy-i',
    minStock: 2,
    updatedAt: new Date().toISOString(),
  },
];
